### ISSUE TITLE
Why mini-batch training not work?

### ISSUE THREAD

**Issue by Myasuka** [davidstutz/matlab-mnist-two-layer-perceptron#1]
Hi, David.

In the file `trainStochasticSquaredErrorTwoLayerPerceptron.m`, the weight matrices are updated after propagating and back-propagating on each item, this is the standard SGD optimize, while I try to use mini-batch optimize. I modify `inputVector = inputValues(:, n(k));`  to `inputVector = inputValues(:, n(k): n(k) + minBatch );` and change `targetVector` to `targetVector = targetValues(:, n(k): n(k) + minBatch);`. I hope the weight matrices are updated `epochs` times, and this looks like the mini-batch way, However, the experimental results are totally wrong, correct percent is only 10%.

Would you explain why?
Thanks

**Comment by Myasuka** [comment]
After I change the input from vector to matrix, in the update weight matrix step,I forget to element-wise divide mini-batch size, that's why mini-batch training not work. I have updated code in my forked respository. https://github.com/Myasuka/matlab-mnist-two-layer-perceptron

**Comment by davidstutz** [comment]
Thanks for the note, will add this note and a link to your fork to the README.
