### ISSUE TITLE
wrong mini-batch code

### ISSUE THREAD

**Issue by manageryzy** [davidstutz/matlab-mnist-two-layer-perceptron#3]
trainStochasticSquaredErrorTwoLayerPerceptron.m line 55
weight is  updated at each sample of minibatch, this is not mini-batch. it's online

**Comment by davidstutz** [comment]
Yes, you're totally right. Unfortunately, I currently don't have access to a MatLab license, so I will leave it like this - the code works neverthelesse, even though it's online training ;)
